# action.yml
name: 'call OB Farm to run task'
description: ''
inputs:
  template_name:
    description: 'template_name'
    required: true
  parameters:
    description: 'parameters'
    required: true
  timeout:
    description: 'timeout'
    required: false
    default: '3600'
outputs:
  success:
    description: 'the status for the task'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.template_name }}
    - ${{ inputs.parameters }}
    - ${{ inputs.timeout }}

