on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Niyuhang2' }}
    name: Unit Test (ODC)
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: get ip
        run: curl ifconfig.me
      - name: action by obfarm
        uses: ./
        id: farm
