on: [push, pull_request]

jobs:
  Unit Test (ODC):
    runs-on: ubuntu-latest
    name: Unit Test (ODC)
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: get ip
        run: curl ifconfig.me
      - name: Run unit test++odc_ut_test++COMMIT=${{ github.sha }}
        uses: ./ # Uses an action in the root directory
        run: echo ${{ github.event.pull_request.head.sha }}
