on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.name == 'oceanbase/oceanbase' }}
    name: Unit Test (ODC)
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: get ip
        run: curl ifconfig.me
      - name: test
        run: eho "123"  
