on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello for test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: get ip
        run: curl ifconfig.me
      - name: run odc_ut
        uses: ./ # Uses an action in the root directory
        id: odc_ut
        env:
          OBFARM_HOST: ${{ secrets.OBFARM_HOST }}
          OBFARM_TOKEN: ${{ secrets.OBFARM_TOKEN }}
        with:
          template_name: odc_ut
          parameters: COMMIT=1c02c0063c08a3ef7c1371ed77c3c7ec3196c08c

      # Use the output from the `hello` step